console.log("Hello World")
console.log("Hola Mundo")
console.log("hello duniya")
console.log("salam")
console.log("welcome")
console.log("benvinguts")
console.log("hi")
console.log("hola")
console.log("buenos dias")
console.log("buenos noches")
console.log("hello ")
console.log("hello ")
console.log("hello ")
console.log("hello ")
console.log("hello")
